<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
	public function getEventByUser($user_id,$limit = 10) {

		return $this->getEntityManager()
			->createQueryBuilder()
			->select('e')
			->from('AppBundle:Event', 'e')
			->leftJoin('e.users','u')
			->leftJoin('e.groupes','g')
			->addSelect('g')
			->leftJoin('g.userGroupes','ug')
			->addSelect('ug')
			->leftJoin('ug.user','ugu')
			->addSelect('ugu')
			->where('e.author != :user_id')
			->andWhere('u.id = :user_id or ugu.id = :user_id')
			->setParameter('user_id', $user_id)
			->orderBy('e.date', 'DESC')
			->setMaxResults($limit)
			->getQuery()
			->getResult();	
	}
	
	public function getEventByGroupe($groupe_id,$limit = 15) {

		return $this->getEntityManager()
			->createQueryBuilder()
			->select('e')
			->from('AppBundle:Event', 'e')
			->innerJoin('e.groupes','g')
			->where('g.id = :groupe_id')
			->setParameter('groupe_id', $groupe_id)
			->orderBy('e.date', 'DESC')
			->setMaxResults($limit)
			->getQuery()
			->getResult();	
	}
	
	public function getEventByPost($post_id) {

		return $this->getEntityManager()
			->createQueryBuilder()
			->select('e')
			->from('AppBundle:Event', 'e')
			->where('e.post = :post_id')
			->setParameter('post_id', $post_id)
			->orderBy('e.date', 'DESC')
			->getQuery()
			->getResult();	
	}
	
	public function getEventByComment($comment_id) {

		return $this->getEntityManager()
			->createQueryBuilder()
			->select('e')
			->from('AppBundle:Event', 'e')
			->where('e.comment = :comment_id')
			->setParameter('comment_id', $comment_id)
			->orderBy('e.date', 'DESC')
			->getQuery()
			->getResult();	
	}
}
