<?php

namespace AppBundle\Repository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends \Doctrine\ORM\EntityRepository
{
	public function getGroupesByUser($userId) {

		return $this->getEntityManager()
			->createQueryBuilder()
			->select('g')
			->from('AppBundle:Groupe', 'g')
			//->innerJoin('p.groupes','g')
			->innerJoin('g.userGroupes','ug')
			->addSelect('ug')
			->innerJoin('ug.user','u')
			->addSelect('u')
			->where('u.id = :user_id')
			->setParameter('user_id', $userId)
			//->orderBy('p.date', 'DESC')
			->getQuery()
			->getResult();	
	}
	
	public function getGroupeBySlugAndUser($groupe_slug,$user_id) {
		
		return $this->getEntityManager()
			->createQueryBuilder()
			->select('g')
			->from('AppBundle:Groupe', 'g')
			//->leftjoin('g.users','u','WITH','u.id = :user_id')
			->leftJoin('g.userGroupes','ug')
			//->addSelect('ug')
			->leftJoin('ug.user','u')
			//->addSelect('u')
			->where('u.id = :user_id OR g.statut = 2')
			->andWhere('g.slug = :groupe_slug')
			//->andWhere('u.id = :user_id')
			->setParameters(array('user_id' => $user_id, 'groupe_slug' => $groupe_slug))
			//->orderBy('p.date', 'DESC')
			->getQuery()
			->getOneOrNullResult();	
	}

}
